name: Pylint Check

on: [push]

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Run Pylint
      run: |
        pylint src --ignore=tests --max-line-length=120 --exit-zero --disable=import-error

    - name: Check Pylint score
      run: |
        pylint_score=$(pylint src --ignore=tests --max-line-length=120 --exit-zero --disable=import-error | grep -oP 'Your code has been rated at \K\d+\.\d+/10')
        pylint_score_numeric=$(echo "$pylint_score" | awk -F '/' '{print $1}')
        if (( $(echo "$pylint_score_numeric >= 8" | bc -l) )); then
          echo "Pylint score is acceptable: $pylint_score"
        else
          echo "Pylint score is too low: $pylint_score"
          exit 1
        fi


